# Generated by Django 3.1.1 on 2021-04-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='emailconfirm',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
