# Generated by Django 3.1.1 on 2021-04-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_emailconfirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_orderd',
            field=models.DateField(auto_now_add=True),
        ),
    ]
