# Generated by Django 3.1.1 on 2021-04-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210427_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_orderd',
            field=models.DateField(auto_now_add=True),
        ),
    ]
