# Generated by Django 3.1.1 on 2021-04-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_order_emailconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='phonenumber',
            field=models.IntegerField(blank=True, default=0, max_length=13, null=True),
        ),
    ]
