# Generated by Django 3.1.1 on 2021-04-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_shippingaddress_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phonenumber',
            field=models.CharField(blank=True, default=0, max_length=13, null=True),
        ),
    ]
