# Generated by Django 3.1.1 on 2021-05-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210506_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
