# Generated by Django 3.1.1 on 2021-06-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_grandtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40, null=True)),
                ('lastname', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('response', models.TextField(max_length=400, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
